extends: stylelint-config-standard-scss
ignoreFiles: "**/*.js"
rules:
  selector-type-no-unknown: null
  declaration-empty-line-before: null
  no-descending-specificity: null
  selector-pseudo-class-no-unknown: null
  color-function-notation: legacy
  alpha-value-notation: number
  scss/operator-no-unspaced: null
  scss/no-global-function-names: null
  scss/dollar-variable-empty-line-before: null
  scss/dollar-variable-pattern: ^[a-z]+(_[a-z]+)*$
  scss/at-mixin-pattern: ^[a-z]+(_[a-z]+)*$
