misc {
    disable_hyprland_logo = 1
    disable_splash_rendering = 1
    focus_on_activate = 1
    allow_session_lock_restore = true
    middle_click_paste = false
    session_lock_xray = 1
}

render {
  direct_scanout = false
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}


scrolling {
  fullscreen_on_one_column = true
  column_width = 0.5
  explicit_column_widths = 0.5,1.0
}

# gestures {
#     workspace_swipe = on
# }

cursor {
  no_hardware_cursors = 2
  no_warps = true
}

opengl {
  nvidia_anti_flicker = true
}

permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
