windowrule {
  name = windowrule-1
  float = on
  match:class = ^(org.gnome.Calculator)$
}


# Picture-in-picture
windowrule {
  name = windowrule-2
  float = on
  move = (1492) (839)
  size = 427 240
  pin = on
  match:title = ^(Picture-in-Picture)$
}


# FL Studio
windowrule {
  name = windowrule-3
  no_blur = on
  match:class = ^(fl64.exe)$
}


# Kitty floating
windowrule {
  name = windowrule-4
  no_screen_share = on
  match:class = ^(librewolf)$
}


# Selection (slurp, grimblast, etc.)
layerrule {
  name = layerrule-1
  no_anim = on
  match:namespace = selection
}


# Idle inhibit when in fullscreen
windowrule {
  name = windowrule-5
  idle_inhibit = on
  fullscreen = on
  match:fullscreen = 1
}


# Audacious
windowrule {
  name = windowrule-6
  rounding = false
  border_size = 0
  no_shadow = on
  match:class = ^Audacious$
}


# Fabric
layerrule {
  name = layerrule-2
  blur = on
  ignore_alpha = 0.4
  match:namespace = fabric
}

# Quickshell
layerrule {
  name = qs
  blur = on
  ignore_alpha = 0.7
  no_anim = true
  match:namespace = quickshell
}
