-- ▄    ▄▄▄  ▄▄ ▄▄  ▄▄▄▄ ▄▄▄▄▄▄ ▄▄    
--  ▀▄ ██▀██ ▀█▄█▀ ██▀▀▀   ██   ██    
-- ▄▀  ██▀██ ██ ██ ▀████   ██   ██▄▄▄ 


-- Generated by axctl LuaGenerator (Keybinds)
-- Do not edit manually!


-- Generated by axctl LuaGenerator (Window Rules)
-- Do not edit manually!


-- Generated by axctl LuaGenerator (Layer Rules)
-- Do not edit manually!

