# ┌──────────────────────────┐
# │                          │
# │     ░█░█░█▀█░▀▀█░▀█▀     │
# │     ░░█░░█▀█░▄▀░░░█░     │
# │     ░░▀░░▀░▀░▀▀▀░▀▀▀     │
# │                          │
# └──────────────────────────┘

[manager]
cwd = { fg = "#5E637C" }

hovered         = { fg = "#5E637C", bg = "#0a0a0f", bold = true, underline = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#6D738E", italic = true }
find_position = { fg = "#7D83A1", bg = "reset", italic = true }

marker_selected = { fg = "#6D738E", bg = "#6D738E" }
marker_copied   = { fg = "#6D738E", bg = "#6D738E" }
marker_cut      = { fg = "#5E637C", bg = "#5E637C" }

tab_active   = { fg = "#0a0a0f", bg = "#8e909e" }
tab_inactive = { fg = "#8e909e", bg = "#0a0a0f" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "#0a0a0f" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#0a0a0f", bg = "#0a0a0f" }

mode_normal = { fg = "#0a0a0f", bg = "#5E637C", bold = true }
mode_select = { fg = "#0a0a0f", bg = "#6D738E", bold = true }
mode_unset  = { fg = "#0a0a0f", bg = "#979EC1", bold = true }

progress_label  = { fg = "#cbcfe2", bold = true }
progress_normal = { fg = "#8e909e", bg = "#0a0a0f" }
progress_error  = { fg = "#5E637C", bg = "#0a0a0f" }

permissions_t = { fg = "#8e909e" }
permissions_r = { fg = "#6D738E" }
permissions_w = { fg = "#5E637C" }
permissions_x = { fg = "#6D738E" }
permissions_s = { fg = "#8e909e" }

[input]
border   = { fg = "#6D738E" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#8e909e" }
active   = { fg = "#7D83A1" }
inactive = {}

[tasks]
border  = { fg = "#8e909e" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#0a0a0f" }
cand            = { fg = "#cbcfe2" }
rest            = { fg = "#8e909e" }
desc            = { fg = "#7D83A1" }
separator       = "  "
separator_style = { fg = "#8e909e" }

[help]
on      = { fg = "#7D83A1" }
exec    = { fg = "#cbcfe2" }
desc    = { fg = "#8e909e" }
hovered = { bg = "#8e909e", bold = true }
footer  = { fg = "#0a0a0f", bg = "#8e909e" }

[filetype]

rules = [
    { mime = "image/*", fg = "#979EC1" },

    { mime = "video/*", fg = "#8C93B4" },
    { mime = "audio/*", fg = "#6D738E" },

    { mime = "application/zip",             fg = "#7D83A1" },
    { mime = "application/gzip",            fg = "#7D83A1" },
    { mime = "application/x-tar",           fg = "#7D83A1" },
    { mime = "application/x-bzip",          fg = "#7D83A1" },
    { mime = "application/x-bzip2",         fg = "#7D83A1" },
    { mime = "application/x-7z-compressed", fg = "#7D83A1" },
    { mime = "application/x-rar",           fg = "#7D83A1" },

    { name = "*", fg = "#8C93B4" },
    { name = "*/", fg = "#cbcfe2" }
]
