# vim:fileencoding=utf-8:foldmethod=marker

# : Manager 

[manager]
cwd = { fg = "#b86467" }

# Hovered
hovered         = { fg = "#b86467", bg = "#000000", bold = true, underline = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#8d987e", italic = true }
find_position = { fg = "#dabd8d", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#8d987e", bg = "#8d987e" }
marker_copied   = { fg = "#8d987e", bg = "#8d987e" }
marker_cut      = { fg = "#b86467", bg = "#b86467" }

# Tab
tab_active   = { fg = "#000000", bg = "#404040" }
tab_inactive = { fg = "#404040", bg = "#0d0d0d" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#111111" }

# Highlighting
# syntect_theme = "~/.config/yazi/Gruvbox-Dark.tmTheme"

# : 


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#111111", bg = "#111111" }

# Mode
mode_normal = { fg = "#000000", bg = "#b86467", bold = true }
mode_select = { fg = "#000000", bg = "#8d987e", bold = true }
mode_unset  = { fg = "#000000", bg = "#ab89b2", bold = true }

# Progress
progress_label  = { fg = "#e9e4e4", bold = true }
progress_normal = { fg = "#181818", bg = "#111111" }
progress_error  = { fg = "#b86467", bg = "#111111" }

# Permissions
permissions_t = { fg = "#181818" }
permissions_r = { fg = "#8d987e" }
permissions_w = { fg = "#b86467" }
permissions_x = { fg = "#8d987e" }
permissions_s = { fg = "#404040" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#8d987e" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#181818" }
active   = { fg = "#dabd8d" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#181818" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#111111" }
cand            = { fg = "#e9e4e4" }
rest            = { fg = "#404040" }
desc            = { fg = "#dabd8d" }
separator       = "  "
separator_style = { fg = "#181818" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#dabd8d" }
exec    = { fg = "#e9e4e4" }
desc    = { fg = "#404040" }
hovered = { bg = "#181818", bold = true }
footer  = { fg = "#111111", bg = "#404040" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#ab89b2" },

    # Videos
    { mime = "video/*", fg = "#80aa9e" },
    { mime = "audio/*", fg = "#8d987e" },

    # Archives
    { mime = "application/zip",             fg = "#dabd8d" },
    { mime = "application/gzip",            fg = "#dabd8d" },
    { mime = "application/x-tar",           fg = "#dabd8d" },
    { mime = "application/x-bzip",          fg = "#dabd8d" },
    { mime = "application/x-bzip2",         fg = "#dabd8d" },
    { mime = "application/x-7z-compressed", fg = "#dabd8d" },
    { mime = "application/x-rar",           fg = "#dabd8d" },

    # Fallback
    { name = "*", fg = "#8ba8a4" },
    { name = "*/", fg = "#e9e4e4" }
]

# : }}}
