[manager]
cwd = { fg = "#413E62" }

hovered         = { fg = "#413E62", bg = "#0d0d11", bold = true, underline = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#3E415D", italic = true }
find_position = { fg = "#4D4D64", bg = "reset", italic = true }

marker_selected = { fg = "#3E415D", bg = "#3E415D" }
marker_copied   = { fg = "#3E415D", bg = "#3E415D" }
marker_cut      = { fg = "#413E62", bg = "#413E62" }

tab_active   = { fg = "#0d0d11", bg = "#7f7f8b" }
tab_inactive = { fg = "#7f7f8b", bg = "#0d0d11" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "#0d0d11" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#0d0d11", bg = "#0d0d11" }

mode_normal = { fg = "#0d0d11", bg = "#413E62", bold = true }
mode_select = { fg = "#0d0d11", bg = "#3E415D", bold = true }
mode_unset  = { fg = "#0d0d11", bg = "#5E5B8A", bold = true }

progress_label  = { fg = "#b6b6c7", bold = true }
progress_normal = { fg = "#7f7f8b", bg = "#0d0d11" }
progress_error  = { fg = "#413E62", bg = "#0d0d11" }

permissions_t = { fg = "#7f7f8b" }
permissions_r = { fg = "#3E415D" }
permissions_w = { fg = "#413E62" }
permissions_x = { fg = "#3E415D" }
permissions_s = { fg = "#7f7f8b" }

[input]
border   = { fg = "#3E415D" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#7f7f8b" }
active   = { fg = "#4D4D64" }
inactive = {}

[tasks]
border  = { fg = "#7f7f8b" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#0d0d11" }
cand            = { fg = "#b6b6c7" }
rest            = { fg = "#7f7f8b" }
desc            = { fg = "#4D4D64" }
separator       = "  "
separator_style = { fg = "#7f7f8b" }

[help]
on      = { fg = "#4D4D64" }
exec    = { fg = "#b6b6c7" }
desc    = { fg = "#7f7f8b" }
hovered = { bg = "#7f7f8b", bold = true }
footer  = { fg = "#0d0d11", bg = "#7f7f8b" }

[filetype]

rules = [
    { mime = "image/*", fg = "#5E5B8A" },

    { mime = "video/*", fg = "#4B4A6F" },
    { mime = "audio/*", fg = "#3E415D" },

    { mime = "application/zip",             fg = "#4D4D64" },
    { mime = "application/gzip",            fg = "#4D4D64" },
    { mime = "application/x-tar",           fg = "#4D4D64" },
    { mime = "application/x-bzip",          fg = "#4D4D64" },
    { mime = "application/x-bzip2",         fg = "#4D4D64" },
    { mime = "application/x-7z-compressed", fg = "#4D4D64" },
    { mime = "application/x-rar",           fg = "#4D4D64" },

    { name = "*", fg = "#4B4A6F" },
    { name = "*/", fg = "#b6b6c7" }
]
