# ┌──────────────────────────┐
# │                          │
# │     ░█░█░█▀█░▀▀█░▀█▀     │
# │     ░░█░░█▀█░▄▀░░░█░     │
# │     ░░▀░░▀░▀░▀▀▀░▀▀▀     │
# │                          │
# └──────────────────────────┘

[manager]
cwd = { fg = "#474C58" }

hovered         = { fg = "#474C58", bg = "#03030D", bold = true, underline = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#575C67", italic = true }
find_position = { fg = "#696F77", bg = "reset", italic = true }

marker_selected = { fg = "#575C67", bg = "#575C67" }
marker_copied   = { fg = "#575C67", bg = "#575C67" }
marker_cut      = { fg = "#474C58", bg = "#474C58" }

tab_active   = { fg = "#03030D", bg = "#898c8c" }
tab_inactive = { fg = "#898c8c", bg = "#03030D" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "#03030D" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#03030D", bg = "#03030D" }

mode_normal = { fg = "#03030D", bg = "#474C58", bold = true }
mode_select = { fg = "#03030D", bg = "#575C67", bold = true }
mode_unset  = { fg = "#03030D", bg = "#7D8288", bold = true }

progress_label  = { fg = "#c5c8c8", bold = true }
progress_normal = { fg = "#898c8c", bg = "#03030D" }
progress_error  = { fg = "#474C58", bg = "#03030D" }

permissions_t = { fg = "#898c8c" }
permissions_r = { fg = "#575C67" }
permissions_w = { fg = "#474C58" }
permissions_x = { fg = "#575C67" }
permissions_s = { fg = "#898c8c" }

[input]
border   = { fg = "#575C67" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#898c8c" }
active   = { fg = "#696F77" }
inactive = {}

[tasks]
border  = { fg = "#898c8c" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#03030D" }
cand            = { fg = "#c5c8c8" }
rest            = { fg = "#898c8c" }
desc            = { fg = "#696F77" }
separator       = "  "
separator_style = { fg = "#898c8c" }

[help]
on      = { fg = "#696F77" }
exec    = { fg = "#c5c8c8" }
desc    = { fg = "#898c8c" }
hovered = { bg = "#898c8c", bold = true }
footer  = { fg = "#03030D", bg = "#898c8c" }

[filetype]

rules = [
    { mime = "image/*", fg = "#7D8288" },

    { mime = "video/*", fg = "#777C83" },
    { mime = "audio/*", fg = "#575C67" },

    { mime = "application/zip",             fg = "#696F77" },
    { mime = "application/gzip",            fg = "#696F77" },
    { mime = "application/x-tar",           fg = "#696F77" },
    { mime = "application/x-bzip",          fg = "#696F77" },
    { mime = "application/x-bzip2",         fg = "#696F77" },
    { mime = "application/x-7z-compressed", fg = "#696F77" },
    { mime = "application/x-rar",           fg = "#696F77" },

    { name = "*", fg = "#777C83" },
    { name = "*/", fg = "#c5c8c8" }
]
