# ┌──────────────────────────┐
# │                          │
# │     ░█░█░█▀█░▀▀█░▀█▀     │
# │     ░░█░░█▀█░▄▀░░░█░     │
# │     ░░▀░░▀░▀░▀▀▀░▀▀▀     │
# │                          │
# └──────────────────────────┘

[manager]
cwd = { fg = "#503146" }

hovered         = { fg = "#503146", bg = "#120f0d", bold = true, underline = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#6A3652", italic = true }
find_position = { fg = "#4B4954", bg = "reset", italic = true }

marker_selected = { fg = "#6A3652", bg = "#6A3652" }
marker_copied   = { fg = "#6A3652", bg = "#6A3652" }
marker_cut      = { fg = "#503146", bg = "#503146" }

tab_active   = { fg = "#120f0d", bg = "#806974" }
tab_inactive = { fg = "#806974", bg = "#120f0d" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "#120f0d" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#120f0d", bg = "#120f0d" }

mode_normal = { fg = "#120f0d", bg = "#503146", bold = true }
mode_select = { fg = "#120f0d", bg = "#6A3652", bold = true }
mode_unset  = { fg = "#120f0d", bg = "#813A5D", bold = true }

progress_label  = { fg = "#b897a6", bold = true }
progress_normal = { fg = "#806974", bg = "#120f0d" }
progress_error  = { fg = "#503146", bg = "#120f0d" }

permissions_t = { fg = "#806974" }
permissions_r = { fg = "#6A3652" }
permissions_w = { fg = "#503146" }
permissions_x = { fg = "#6A3652" }
permissions_s = { fg = "#806974" }

[input]
border   = { fg = "#6A3652" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#806974" }
active   = { fg = "#4B4954" }
inactive = {}

[tasks]
border  = { fg = "#806974" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#120f0d" }
cand            = { fg = "#b897a6" }
rest            = { fg = "#806974" }
desc            = { fg = "#4B4954" }
separator       = "  "
separator_style = { fg = "#806974" }

[help]
on      = { fg = "#4B4954" }
exec    = { fg = "#b897a6" }
desc    = { fg = "#806974" }
hovered = { bg = "#806974", bold = true }
footer  = { fg = "#120f0d", bg = "#806974" }

[filetype]

rules = [
    { mime = "image/*", fg = "#813A5D" },

    { mime = "video/*", fg = "#615D6B" },
    { mime = "audio/*", fg = "#6A3652" },

    { mime = "application/zip",             fg = "#4B4954" },
    { mime = "application/gzip",            fg = "#4B4954" },
    { mime = "application/x-tar",           fg = "#4B4954" },
    { mime = "application/x-bzip",          fg = "#4B4954" },
    { mime = "application/x-bzip2",         fg = "#4B4954" },
    { mime = "application/x-7z-compressed", fg = "#4B4954" },
    { mime = "application/x-rar",           fg = "#4B4954" },

    { name = "*", fg = "#615D6B" },
    { name = "*/", fg = "#b897a6" }
]
