[nvchad]
source = "colors-nvchad.lua"
target = "~/.config/nvim/lua/themes/wal.lua"
command = "python ~/.config/wal/reload_nvim.py"

[discord]
source = "colors-discord.css"
target = "~/.config/vesktop/themes/axwal.theme.css"

[hyprland]
source = "colors-hyprland.conf"
target = "~/.config/hypr/source/colors.conf"

[fabric]
source = "colors-fabric.css"
target = "~/.config/fabric/bar/styles/themes/wal.css"
command = "python ~/.config/fabric/bar/scripts/send.py update-style"

[zathura]
source = "colors-zathura"
target = "~/.config/zathura/zathurarc"

[pywalfox]
command = "pywalfox update"

[telegram]
command = "walogram -B"

[test]
command = "notify-send 'HEYYYYYYY'"
