[config]
reload_apps = true

[config.reload_apps_list]
kitty = true
gtk_theme = true

[config.wallpaper]
command = "swww"
arguments = ["img", "-t", "outer", "--transition-duration", "1.5", "--transition-step", "255", "--transition-fps", "60", "-f", "Nearest"]
set = true

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/source/colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = "killall -SIGUSR1 kitty &"

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/matugen'

[templates.slurp]
input_path = '~/.config/matugen/templates/colors-slurp.sh'
output_path = '~/.config/kitty/slurp.sh'

[templates.fabric]
input_path = '~/.config/matugen/templates/fabric.css'
output_path = '~/.config/fabric/styles/colors.css'
post_hook = "fabric-cli exec ax-shell 'app.set_stylesheet_from_file(get_relative_path(\"main.css\"))' &"

[templates.gtk3]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.nvim]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-dark.lua'

[templates.discord]
input_path = '~/.config/matugen/templates/discord-colors.theme.css'
output_path = '~/.config/vesktop/themes/axnight.theme.css'

[templates.pywaljson]
input_path = '~/.config/matugen/templates/pywal-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = "pywalfox update &"

[templates.pywalsh]
input_path = '~/.config/matugen/templates/colors.sh'
output_path = '~/.cache/wal/colors.sh'
post_hook = "walogram -B > /dev/null 2>&1 &"

[templates.pywalwalfile]
input_path = '~/.config/matugen/templates/wal'
output_path = '~/.cache/wal/wal'

[templates.rofi]
input_path = '~/.config/matugen/templates/colors-rofi.rasi'
output_path = '~/.cache/wal/colors-rofi.rasi'

[templates.zathura]
input_path = '~/.config/matugen/templates/colors-zathura'
output_path = '~/.config/zathura/zathurarc'

[templates.yazi]
input_path = '~/.config/matugen/templates/colors-yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify-color.ini'
output_path = '~/.config/spicetify/Themes/Dribbblish/color.ini'
post_hook = "bash ~/.config/matugen/scripts/spicetify.sh &"
